.TH 明日がないIFへの慰め 1 2023-08-31 プログラミング系ネタツイ
.SH 名前
明日がないIFへの慰め \- カウンセラープログラム
.SH 書式
.B 明日がないIFへの慰め
.SH 説明
.PP
明日がないIFへの慰め
は、ユーザに明日があるかどうかを質問します。この質問に対して、
「有る」「無い」のいずれかを入力して回答してください。
それぞれの回答に応じたアドバイスをします。
.PP
なお、それ以外の入力をした場合、このプログラムは混乱します。
.SH オプション
.PP
受け取りません。
.SH 終了ステータス
.PP
例えばこんな感じのとかどうですか。
.TP
.B 0
想定していた回答を受け取れた。
.TP
.B >0
それ以外のシチュエーション。
.SH 環境変数
.PP
例えばこんな感じのとかどうですか。
.TP
.BR LANG ", " LC_MESSAGES
プログラムからの質問とアドバイスやユーザの回答に使う言語を表すロケール。
.SH 規格
.PP
定まっていません。
でも、質問、受け付ける回答、それに対する返答の形式は引用ポストを
眺めているところ、統一されているようです。
.SH 歴史
.PP
\(dq明日がないIFへの慰め\(dqという言葉は、
.B 全てあなたの所以です。
さんが2022年11月にYouTubeにて公開した作品
.UR "https://youtu.be/tJjPofpVwdU"
.RB 『 "#[short]" 』
.UE
に登場する歌詞が元ネタとされています(独自研究)。
.PP
明日がないIFへの慰めプログラムの初出は誰か書いてください。正直どうでもいいです。
.SH その他
.PP
一部の実装では、「有る」「無い」ではなく「ある」「ない」などの
異なる表記の回答を受け付ける場合があります。
.SH 注意
.PP
一部の実装は端末そのものではなく標準入出力を通じて入出力を行っています。
.PP
このプログラムは、スクリプト用に意図して作られたものではありません。
対話的に使用することを推奨します。
.SH バグ
.PP
例えば質問するときにどう回答すべきなのかを教えてくれたっていいんじゃない？
.SH 著作権
.SS プログラムの著作権
.PP
実装した人を探してくれ。そしてライセンスは各自に聞いてくれ。
.SS このマニュアルの著作権
.PP
Copyright \(co 2023 Tpaefawzen
.PP
と書くけど、正直わざわざ示さなくてもよくなーい？
ネタツイへの引用リポストだよ？
誰かパクってくれ。
.SH 関連項目
.PP
あるわけねえだろ、
.PP
カ
.PP
ス
