.Dd $Mdocdate: August 31 2023 $
.Dt 明日がないIFへの慰め 1
.Os
.Sh NAME
.Nm 明日がないIFへの慰め
.Nd カウンセラープログラム
.Sh 名前
mdoc(7)に物申す!なんで英語でNAME節のところでNmとNdじゃないといけないんだ!
最初の節のNmとNdで本当の名前はコレだっていうことを受け付けたっていいじゃないか!
こっちはなあ!日本語でマニュアルを書いてるんだぞ!
.Sh 書式
.B 明日がないIFへの慰め
.Sh 説明
.Nm
は、ユーザに明日があるかどうかを質問します。この質問に対して、
.Dq 有る
.Dq 無い
のいずれかを入力して回答してください。
それぞれの回答に応じたアドバイスをします。
.Pp
なお、それ以外の入力をした場合、このプログラムは混乱します。
.Sh その他
一部の実装では、
.Dq 有る
.Dq 無い
ではなく
.Dq ある
.Dq ない
などの異なる表記の回答を受け付ける場合があります。
.Sh 環境変数
例えばこんな感じのとかどうですか。
.Bl -tag
.It Ev LANG , LC_MESSAGES
プログラムからの質問とアドバイスやユーザの回答に使う言語を表すロケール。
.El
.Sh 終了ステータス
例えばこんな感じのとかどうですか。
.Bl -tag
.It 0
想定していた回答を受け取れた。
.It >0
それ以外のシチュエーション。
.El
.Sh 関連項目
.Pp
あるわけねえだろ、
.Pp
カ
.Pp
ス
.Sh 規格
定まっていません。
でも、質問、受け付ける回答、それに対する返答の形式は引用ポストを
眺めているところ、統一されているようです。
.Sh 歴史
.Dq Nm
という言葉は、
.An 全てあなたの所以です。
さんが2022年11月にYouTubeにて公開した作品
.Dq Lk "https://youtu.be/tJjPofpVwdU" "#[short]"
に登場する歌詞が元ネタとされています(独自研究)。
.Pp
.Nm
プログラムの初出は誰か書いてください。正直どうでもいいです。
.Sh 作者
.Ss プログラムの作者
実装した人を探してくれ。そしてライセンスは各自に聞いてくれ。
.Ss このマニュアルの作者
Copyright \(co 2023
.An Tpaefawzen
.Pp
と書くけど、正直わざわざ示さなくてもよくなーい？
ネタツイへの引用リポストだよ？
誰かパクってくれ。
.Sh 注意
一部の実装は端末そのものではなく標準入出力を通じて入出力を行っています。
.Pp
このプログラムは、スクリプト用に意図して作られたものではありません。
対話的に使用することを推奨します。
.Sh バグ
例えば質問するときにどう回答すべきなのかを教えてくれたっていいんじゃない？
.Sh セキュリティ考慮点
標準入出力のリダイレクト使ったらなんかヤバくない？
